# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
       # Step to install Postman CLI on Ubuntu
    - name: Install Postman CLI
      run: |
        curl -L https://dl-cli.pstmn.io/install/win64.sh | sh

    # Step to login to Postman CLI with API Key
    - name: Login to Postman CLI
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      run: postman login --with-api-key $POSTMAN_API_KEY

    # Step to run Postman collection tests
    - name: Run API tests
      run: |
        postman collection run "${{ github.workspace }}/postman/collections/SalesCollection.json"
